[package]
name = "gleezy"
version = "0.1.0"
edition = "2024"

[workspace]
members = [ "lib/gleezy-ast","lib/gleezy-lex", "lib/gleezy-parse", "lib/gleezy-report"]

[dependencies]
gleezy-lex = { path = "lib/gleezy-lex" }
gleezy-parse = { path = "lib/gleezy-parse" }
